#spring.application.name=procash
#spring.datasource.url=jdbc:postgresql://localhost:5432/procash
#spring.datasource.username=procah_user
#spring.datasource.password=procash_password
#
#spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.open-in-view=false
#
#spring.flyway.enabled=true
#spring.thymeleaf.cache=false
#
#procash.public-base-url=http://localhost:8080
spring.application.name=procash
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/procash}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:procash_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:procash_password}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true
spring.thymeleaf.cache=${SPRING_THYMELEAF_CACHE:false}
procash.public-base-url=${PROCASH_PUBLIC_BASE_URL:http://localhost:8080}
server.forward-headers-strategy=framework